#!/usr/bin/env node --harmony

var _ = require('lodash');
var Promise = require('bluebird');
var util = require('util');
var fs = Promise.promisifyAll(require('fs'));
var co = require('co');


var updateFile = co.wrap(function*(file) {
  var contents = yield fs.readFileAsync(file, { encoding: 'utf8' });

  // var r = /expect\(adapter\.executedSQL\)\.to\.eql\([\s\S]*?(\[[\s\S]*?([^]*?)[\s\S]*?\])[\s\S]*?\);/gi;

  var r = /expect\(adapter\.executedSQL\)\.to\.eql\([\s\n]*?\[[\s\n]*?([^]*?)[\s\n]*?\][\s\n]*?\);/gi;

  var matches = contents.match(r);

  contents = contents.replace(r, function(match, p1) {
    // console.log(p1)
    // console.log('>>>>>')
    p1 = p1.replace(/\[('[^]*?'),\s*\[([^]*?)\]\s*\]/g, function(match, p1, p2) {
      // console.log(util.format('%s, [%s]', p1, p2).replace(', []', ''))
      return util.format('%s, [%s]', p1, p2).replace(', []', '');

    });
    // console.log('<<<<<')

    // console.log(arguments[1])
    // console.log(arguments[2])
    // return match
    return util.format('adapter.should.have.executed(%s);', p1);
  });
  // matches = matches || [];
  // matches.forEach(func)

  // console.log(matches.length)
  // console.log(contents)
  yield fs.writeFileAsync(file, contents);
});

Promise.all(process.argv.slice(2))
.map(updateFile)
.then(function() {
  console.log('done');
});
