#!/usr/bin/env bash

# note that $GITHUB_REPO contains an API key in it, so be careful to not allow
# that to end up as part of the output ever.

set -e

NAME=`git describe --exact-match 2> /dev/null || true`

if [ -z "${NAME}" ]; then
  NAME="master"
fi

if [ "`git rev-parse HEAD`" != "`git rev-parse ${NAME}~0 2> /dev/null`" ]; then
  echo "Not deploying docs for non-master non-tagged commit `git rev-parse --short HEAD`"
  exit 0
fi

mkdir -p deploy
cd deploy
git clone -q --depth 1 --branch gh-pages --single-branch $GITHUB_REPO .
git config user.name $GITHUB_NAME
git config user.email $GITHUB_EMAIL

find . -type f -not -name README.md -not -path './.*' -exec rm {} \;
cp -r ../docs/build/* .

git add -A .
git commit -m 'Site updated' || echo 'No update required.'
git push -q origin gh-pages
